cad = """<AMO FAZER EXERCICIO NO URI>
<    AMO FAZER EXERCICIO NO URI>
<AMO FAZER EXERCICIO >
<AMO FAZER EXERCICIO NO URI>
<AMO FAZER EXERCICIO NO URI    >
<AMO FAZER EXERCICIO NO URI>
<          AMO FAZER EXERCICIO >
<AMO FAZER EXERCICIO           >"""
cadL = cad.split("\n")
for x in cadL:
    print(x)
